### ISSUE TITLE
Generate certificate for i.MXRT1011 with error message

### ISSUE THREAD

**Issue by Laco0072** [JayHeng/NXP-MCUBootUtility#166]
Traceback (most recent call last):
  File "_main\RTyyyy_main.py", line 370, in callbackGenCert
  File "_main\RTyyyy_main.py", line 354, in _doGenCert
  File "gen\RTyyyy_gencore.py", line 207, in genCertificate
WindowsError: [Error 267] The directory name is invalid: 'c:\\NXP-MCUBootUtility\\tools\\cst\\keys'

**Comment by Laco0072** [comment]
error message caused by missing HAB code signing tool
